name: CI Pipeline

on:
  push:
    branches: [main, task5]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Python syntax check
        run: python -m compileall .

      - name: Check project structure
        run: |
          echo "Checking required folders"
          test -d src
          test -d medical_warehouse
          test -d api
          test -d data/raw