models:
  - name: fct_image_detections
    description: YOLOv8 object detections extracted from Telegram images

    columns:
      - name: message_id
        tests:
          - not_null

      - name: detected_object
        tests:
          - not_null

      - name: confidence
        tests:
          - not_null